### ISSUE TITLE
Can't extract hevc from newest iPhone's photos

### ISSUE THREAD

**Issue by mattiabress** [AterCattus/heif_extractor#1]
Good morning
I really appreciate your code, but I have a problem with your code i can extract the hevc from iphone 7 photos but not from the newest iphone.
can you tell me why, and how I can do this.
I attach a photo of the error

I will really appreciate your reply
``
<img width="311" alt="Screenshot 2022-12-01 at 10 17 20" src="https://user-images.githubusercontent.com/62152973/205014168-f97ee390-b3a1-4647-898b-2955938816fc.png">

**Comment by atercattus** [comment]
Hello.
I didn't use this library for several years. 
I can try to debug this problem, but I have no iPhones :)

All what I can now is wish you good luck.
